### ISSUE TITLE
No data was written to the real db, all data is in Memory

### ISSUE THREAD

**Issue by Panl** [marcoarment/Blackbird#10]
I just create a new app and follow the tutorial in README,
After specifying a db path, the db was successfully created, but all the write(to: db) are not actually written to the db, but in memory. If the app is killed and restarted, no data will be left.

iOS 16.2, Simulator
iOS 16.3, 12 mini

**Comment by marcoarment** [comment]
Hi Lei, can you share your code for the `db` initialization?

Blackbird supports in-memory databases and file-based databases. The file-based initialization looks like this:

```swift
let db = try Blackbird.Database(path: completeFilePath)
```

**Comment by Panl** [comment]
```Swift
let dbPath = "\(NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0])/db.sqlite"

@main
struct AICatApp: App {
    var database = try! Blackbird.Database(path: dbPath, options: .debugPrintEveryQuery)
    var body: some Scene {
        WindowGroup {
            ContentView()
                .environment(\.blackbirdDatabase, database)
        }
    }
}
```
```Swift
 func queryMessages() {
        Task {
            guard let db else { return }
            messages = (try? await ChatMessage.read(from: db, matching: \.$conversationId == conversation.id, orderBy: .ascending(\.$timeCreated))) ?? []
            print("--message-count: \(messages.count)")
        }
    }

    func completeMessage() {
        isSending = true
        let sendText = inputText
        inputText = ""
        let chatMessage = ChatMessage(role: "user", content: sendText, conversationId: conversation.id)
        Task {
            if let db {
                try? await chatMessage.write(to: db)
                queryMessages()
            }
            let result = await CatApi.complete(content: sendText)
            switch result {
            case .success(let success):
                saveMessage(response: success)
            case .failure(let failure):
                print("\(failure)")
            }
            isSending = false
        }
    }

    func saveMessage(response: CompleteResponse) {
        if let message = response.choices.first?.message {
            let chatMessage = ChatMessage(role: message.role, content: message.content, conversationId: conversation.id)
            if let db {
                Task {
                    try? await chatMessage.write(to: db)
                    queryMessages()
                }
            }
        }
    }
```

<img width="347" alt="image" src="https://user-images.githubusercontent.com/3842675/226187481-11fc2699-5ce6-42f5-99bc-baea599bce6f.png">

<img width="442" alt="image" src="https://user-images.githubusercontent.com/3842675/226187510-f54ba340-5b78-4833-9f52-6e7b399b8342.png">

![image](https://user-images.githubusercontent.com/3842675/226187591-f22cd99f-c5db-4041-bbb8-9ffa6b0d4dd1.png)

I do have data in memory, but no data in db

Thanks

**Comment by marcoarment** [comment]
Without seeing all of your code, it's hard to tell what the issue is, but is it possible that the `db` value in the second class is defined as a different database instance than the `@Environment` database in the SwiftUI `App` struct?

I'd also caution against using `try?` to suppress the DB-write errors — it looks like the database is important enough to the app's functionality that you may not want it silently failing.

**Comment by Panl** [comment]
My whole project is [here](https://github.com/Panl/AICat.git), just a chat demo

**Comment by marcoarment** [comment]
You found a bug! Thank you. Fixed.
