### ISSUE TITLE
Restricted Combine row monitoring

### ISSUE THREAD

**Issue by thealpa** [marcoarment/Blackbird#18]
I am not sure if this was intended but the following [README.md](https://github.com/marcoarment/Blackbird/blob/main/README.md) example for monitoring row-level changes does not work anymore since the access level of these properties got changed to `internal` in 4b822c0.

```swift
let listener = Post.changePublisher(in: db).sink { change in
    print("Post IDs changed: \(change.primaryKeys ?? "all")")
    print(" Columns changed: \(change.columnNames ?? "all")")
}
```

**Comment by marcoarment** [comment]
Thanks! Fixed.
