### ISSUE TITLE
Support SPM compatible tags

### ISSUE THREAD

**Issue by PetterBraka** [marcoarment/Blackbird#19]
Currently SPM isn't supported as the tags are prefixed with `v`. 
Please could you support SPM compatible tags by changing your tag from `v0.5` to `0.5`?

**Comment by marcoarment** [comment]
Thanks for alerting me to this problem. I think I've fixed it now — can you confirm?

**Comment by PetterBraka** [comment]
It works great now and thank you for the quick fix :)
