### ISSUE TITLE
Make non-nested transactions work reliably

### ISSUE THREAD

**Issue by gnachman** [marcoarment/Blackbird#25]
In SQLite, save points must be used in a nested fashion. This pattern gets you in trouble:

```
SAVEPOINT "1"
SAVEPOINT "2"
RELEASE SAVEPOINT "1"  // This will implicitly release savepoint 2
RELEASE SAVEPOINT "2" // sqlite_exec will return an error causing Blackbird to throw an exception
```

Blackbird makes it easy to do this by accident when using Swift concurrency because it does not force savepoints to be released in a valid order.

For example, the following code may throw an exception depending on the order the transactions begin and end in.
```
Task {
  try await db.cancellableTransaction { core in
     …
  }
}
Task {
  try await db.cancellableTransaction { core in
     …
  }
}
```

The exception looks like this:

```
Blackbird.Blackbird.Database.Error.queryError(query: "ROLLBACK TO SAVEPOINT \"98\"", description: "SQLite error code 1: no such savepoint: 98")
```

I don't know what the best answer is. I believe GRDB has already solved this problem, so copying what they did is worth considering. A possible solution, which I'll be implementing as a hack in my own app, would be to make `ROLLBACK TO/RELEASE SAVEPOINT` wait until all subsequently created savepoints have been released. This risks creating a deadlock, but my intuition is that it would only be possible with gross abuse of Swift concurrency.

I've attached an xcode project that reproduces the problem.

[BlackbirdBug.zip](https://github.com/marcoarment/Blackbird/files/14226086/BlackbirdBug.zip)

**Comment by marcoarment** [comment]
Thanks!

I've fixed it by using an async semaphore within the Core's transaction method when the caller is using an async body. This does completely fix it, but has the possibility of deadlocking if a transaction to the same database is nested within the action block of another one.

I think that's a remote enough possibility that, for now, I'll tolerate that shortcoming.
