### ISSUE TITLE
Type reflection for automatic/cleaner schema definitions

### ISSUE THREAD

**Issue by jjrscott** [marcoarment/Blackbird#6]
Because `BlackbirdModel` extends `Decodable` it's possible to construct an empty instance of the correct type in order to interrogate it. I've created a package to do just that at https://github.com/jjrscott/EmptyInitializer but it's easy to roll your own, especially as you've already done it once (`BlackbirdSQLiteDecoder`).

```swift
let mirror = try Mirror(reflecting: EmptyInitializer.initialize(type: Post.self))
```

This doesn't solve all the issues however as property wrappers don't always do what one would expect when interacting with `Decodable`. Hopefully people comment on [Property wrapper initialisation issues](https://forums.swift.org/t/property-wrapper-initialisation-issues/62407) to either show what I did wrong or propose a fix.

**Comment by marcoarment** [comment]
This is incredible! I've been able to make significant improvements thanks to this trick. You'll see them soon.

Thank you so much!

**Comment by marcoarment** [comment]
Bam!
