### ISSUE TITLE
FYI, marco's git username not set correctly when contributing

### ISSUE THREAD

**Issue by jgstew** [marcoarment/Blackbird#9]
@marcoarment  FYI, you don't have your username and/or email configured to match your github user when you contribute code to this repo so your contributions don't show up associated with your github user account.

See here: https://github.com/marcoarment/Blackbird/commits/main

<img width="492" alt="image" src="https://user-images.githubusercontent.com/2439367/219204008-6214a75d-1f58-4ffb-adf3-0a41f885ba2a.png">

In the above screenshot, the commit from Jan 17th is done through the GitHub interface and is correctly associated, while the commits on Jan 23rd are done locally and then pushed, but GitHub isn't associating them with @marcoarment user account.

This can be configured just for this repo locally on the mac you contribute / push to this repo from.

I think it is just: `git config user.name "marcoarment"` (on the command line within the repo folder)

It might also require configuring the email address to match as well, but I am not certain.

**Comment by marcoarment** [comment]
Fixed. Thanks!
